In [3]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
from IPython import embed
#import pandas_profiling #(runtime is high)

def load_data(file_name):
    csv_path = os.path.join(file_name)
    return pd.read_csv(csv_path)

import os

In [4]:
df_train_1 = load_data('train.csv')
df_train_2 = load_data('building_structure.csv')
df_train_3 = load_data('building_ownership.csv')
df_train_4 = load_data('ward_demographic_data.csv')
df_train_target_1 = df_train_1['damage_grade']

In [6]:
df_1_2 = pd.merge(df_train_1, df_train_2, on=['building_id'])
#df_1_2_3 = pd.merge(df_1_2, df_train_3, on=['df_train_1.df_1_2.building_id', 'df_train_3.building_id' ])
# descriptive: 515937 rows × 35 columns (df_1_2)


df_1_2_3 = pd.merge(df_1_2, df_train_3, on=['building_id','district_id','vdcmun_id','ward_id'])
# descriptive: 515937 rows × 48 columns

In [8]:
df_1_2_3

,building_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,damage_grade,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,44314,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
1,267748,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
2,84477,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
3,17679,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
4,715499,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
5,272416,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,284945,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
7,237367,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
8,282215,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
9,200826,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
10,282336,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
11,395693,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
12,211847,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
13,158953,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
14,708323,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
15,701202,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
16,18238,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
17,104457,1,0,1,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
18,52905,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
19,372057,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
20,269933,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
21,520250,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
22,538466,1,0,0,0,1,0,0,1,2,...,0,0,0,0,0,0,0,0,0,0
23,660719,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,217352,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
25,165616,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
26,583152,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
27,173559,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
28,602562,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
29,555950,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515907,216902,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515908,5833,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
515909,553586,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515910,637379,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515911,243357,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515912,323383,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515913,460716,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515914,480544,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
515915,155887,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
515916,471513,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
515917,220697,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515918,442942,1,1,0,1,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515919,27291,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515920,117376,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515921,170320,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515922,288783,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515923,142285,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515924,421790,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515925,200701,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515926,73013,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515927,466720,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515928,729463,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515929,472353,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515930,56545,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515931,351674,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515932,190306,0,0,0,0,0,0,0,0,5,...,0,1,0,0,0,0,0,0,0,0
515933,602473,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515934,96616,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
515935,392323,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515936,392875,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0

In [9]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import json
import uuid
import pickle

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import math
import sklearn.metrics as metrics

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
#print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

# DataSet Read
#df = pd.read_csv("../input/MiningProcess_Flotation_Plant_Database.csv",decimal=",")
# Delete date column

#df_1_2_3

,building_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,damage_grade,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,44314,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
1,267748,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
2,84477,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
3,17679,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
4,715499,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
5,272416,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,284945,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
7,237367,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
8,282215,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
9,200826,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
10,282336,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
11,395693,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
12,211847,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
13,158953,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
14,708323,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
15,701202,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
16,18238,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
17,104457,1,0,1,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
18,52905,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
19,372057,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
20,269933,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
21,520250,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
22,538466,1,0,0,0,1,0,0,1,2,...,0,0,0,0,0,0,0,0,0,0
23,660719,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,217352,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
25,165616,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
26,583152,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
27,173559,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
28,602562,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
29,555950,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515907,216902,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515908,5833,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
515909,553586,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515910,637379,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515911,243357,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515912,323383,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515913,460716,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515914,480544,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
515915,155887,0,0,0,0,0,0,0,0,5,...,1,0,0,0,0,0,0,0,0,0
515916,471513,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
515917,220697,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515918,442942,1,1,0,1,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515919,27291,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515920,117376,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515921,170320,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515922,288783,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515923,142285,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
515924,421790,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515925,200701,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515926,73013,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515927,466720,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
515928,729463,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515929,472353,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515930,56545,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
515931,351674,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515932,190306,0,0,0,0,0,0,0,0,5,...,0,1,0,0,0,0,0,0,0,0
515933,602473,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515934,96616,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
515935,392323,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
515936,392875,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0

In [124]:
# 'position'
df_train_final = df_1_2_3[[ 'district_id', 
               'has_superstructure_mud_mortar_stone', 
               'plinth_area_sq_ft',  
               'height_ft_pre_eq', 
               'has_geotechnical_risk', 
               'has_superstructure_timber', 
               'count_floors_pre_eq', 
               'age_building', 
               'damage_grade',
              'building_id']]
train, test = train_test_split(df_train_final, test_size=0.2)
print ('# train:',len(train))
print ('# test: ',len(test))

# train: 412749
# test:  103188

In [125]:
df_train_final.columns

Index(['district_id', 'has_superstructure_mud_mortar_stone',
       'plinth_area_sq_ft', 'height_ft_pre_eq', 'has_geotechnical_risk',
       'has_superstructure_timber', 'count_floors_pre_eq', 'age_building',
       'damage_grade', 'building_id'],
      dtype='object')

In [126]:
# Extract column to predict on train X
X = train.drop('damage_grade', axis=1)
X.head(20)

,district_id,has_superstructure_mud_mortar_stone,plinth_area_sq_ft,height_ft_pre_eq,has_geotechnical_risk,has_superstructure_timber,count_floors_pre_eq,age_building,building_id
305962,28,0,450,18,1,0,2,34,449143
148235,11,1,460,27,0,1,3,50,22940
142625,22,1,448,17,0,0,3,11,163511
461833,23,1,459,14,1,0,2,8,222437
385184,31,1,205,16,0,1,2,20,586708
306158,26,0,785,21,1,0,3,33,368608
411668,24,1,395,16,0,0,2,5,272505
241884,31,1,247,14,1,0,2,9,585933
66395,31,0,225,12,0,0,1,1,552217
107926,35,0,634,9,1,0,1,13,597742
254828,31,0,476,16,0,1,2,2,584323
116508,22,1,370,14,0,0,2,30,173503
358094,30,1,265,14,0,1,2,15,484619
39734,30,0,855,27,0,0,3,10,513030
170506,51,1,600,17,0,0,3,40,736576
185442,30,1,70,12,0,1,2,15,489785
23710,28,1,820,20,1,0,3,7,406383
138439,47,1,290,19,0,0,2,13,735124
176093,20,0,380,8,0,0,1,7,81981
500687,37,0,693,18,0,0,2,10,672799

In [127]:
# Create train y
y = train['damage_grade']
y.head(20)

305962    5
148235    4
142625    3
461833    5
385184    1
306158    3
411668    3
241884    3
66395     1
107926    1
254828    1
116508    4
358094    4
39734     1
170506    2
185442    5
23710     4
138439    4
176093    1
500687    1
Name: damage_grade, dtype: int64

In [128]:
# Model creation and fit
model = RandomForestRegressor()
model.fit(X,y)

/Users/danielmueller/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [129]:
# Show model results of training set
y_hat = model.predict(X)
mae = metrics.mean_absolute_error(y,y_hat)
mse = metrics.mean_squared_error(y,y_hat)
print ("TRAINING SET")
print ("============")
print ("MAE:                ", mae)
print ("RMSE:               ", math.sqrt(mse))
print ("r2:                 ", model.score(X,y))
print ("feature_importances:",model.feature_importances_)
print ("n_features:         ",model.n_features_)
print ("n_outputs:          ",model.n_outputs_)
print ("XXX is the highest feature_importances")

TRAINING SET
============
MAE:                 0.2592507795294476
RMSE:                0.3900134402954661
r2:                  0.9136283046528255
feature_importances: [0.00590389 0.09917825 0.12073704 0.066422   0.00888724 0.01389574
 0.01314964 0.16213509 0.50969113]
n_features:          9
n_outputs:           1
XXX is the highest feature_importances

In [130]:
# Use test and show results of test set
X= test.drop('damage_grade', axis=1)
y= test['damage_grade']
y_hat = model.predict(X)
mae = metrics.mean_absolute_error(y,y_hat)
mse = metrics.mean_squared_error(y,y_hat)
print ("TEST SET")
print ("========")
print ("MAE:                ", mae)
print ("RMSE:               ", math.sqrt(mse))
print ("r2:                 ", model.score(X,y))

TEST SET
========
MAE:                 0.6757171376516649
RMSE:                0.9301140389441194
r2:                  0.5095729963203459

In [131]:
df_test = load_data('test.csv')

In [132]:
df_test.columns

Index(['building_id', 'has_geotechnical_risk',
       'has_geotechnical_risk_fault_crack', 'has_geotechnical_risk_flood',
       'has_geotechnical_risk_land_settlement',
       'has_geotechnical_risk_landslide', 'has_geotechnical_risk_liquefaction',
       'has_geotechnical_risk_other', 'has_geotechnical_risk_rock_fall'],
      dtype='object')

In [133]:
df_test[:5]

,building_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall
0,680648,0.0,0,0,0,0,0,0,0
1,339540,1.0,0,0,1,0,0,0,0
2,487192,0.0,0,0,0,0,0,0,0
3,571276,0.0,0,0,0,0,0,0,0
4,326396,0.0,0,0,0,0,0,0,0

,building_id,district_id,vdcmun_id,ward_id,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,1,7,701,70102,Private,1.0,0.0,0,0,0,0,0,0,0,0,0,0
1,2,7,701,70103,Private,1.0,0.0,0,0,0,0,0,0,0,0,0,0
2,3,7,701,70103,Private,1.0,0.0,0,0,0,0,0,0,0,0,0,0
3,4,7,701,70105,Private,1.0,0.0,0,0,0,0,0,0,0,0,0,0
4,5,7,701,70105,Private,1.0,0.0,0,0,0,0,0,0,0,0,0,0

In [134]:
df_test_structure = pd.merge(df_test, df_train_2, on=['building_id'])



#df_train_1 = load_data('train.csv')
#df_train_2 = load_data('building_structure.csv')
#df_train_3 = load_data('building_ownership.csv')
#df_train_4 = load_data('ward_demographic_data.csv')

In [135]:
df_test_structure_own = pd.merge(df_test_structure, df_train_3, on=['building_id','district_id','vdcmun_id','ward_id'])

In [136]:
df_test_structure_own[:5].columns

Index(['building_id', 'has_geotechnical_risk',
       'has_geotechnical_risk_fault_crack', 'has_geotechnical_risk_flood',
       'has_geotechnical_risk_land_settlement',
       'has_geotechnical_risk_landslide', 'has_geotechnical_risk_liquefaction',
       'has_geotechnical_risk_other', 'has_geotechnical_risk_rock_fall',
       'district_id', 'vdcmun_id', 'ward_id', 'count_floors_pre_eq',
       'age_building', 'plinth_area_sq_ft', 'height_ft_pre_eq',
       'land_surface_condition', 'foundation_type', 'roof_type',
       'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'legal_ownership_status', 'count_families', 'has_secondary_use',
       'has_secondary_use_agriculture', 'has_secondary_use_hotel',
       'has_secondary_use_rental', 'has_secondary_use_institution',
       'has_secondary_use_school', 'has_secondary_use_industry',
       'has_secondary_use_health_post', 'has_secondary_use_gov_office',
       'has_secondary_use_use_police', 'has_secondary_use_other'],
      dtype='object')

In [137]:
df_train_2[:5].columns

Index(['building_id', 'district_id', 'vdcmun_id', 'ward_id',
       'count_floors_pre_eq', 'age_building', 'plinth_area_sq_ft',
       'height_ft_pre_eq', 'land_surface_condition', 'foundation_type',
       'roof_type', 'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other'],
      dtype='object')

In [138]:
df_test_structure_own[:5]

,building_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,district_id,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,680648,0.0,0,0,0,0,0,0,0,38,...,0,0,0,0,0,0,0,0,0,0
1,339540,1.0,0,0,1,0,0,0,0,25,...,0,0,0,0,0,0,0,0,0,0
2,487192,0.0,0,0,0,0,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
3,571276,0.0,0,0,0,0,0,0,0,31,...,0,0,0,0,0,0,0,0,0,0
4,326396,0.0,0,0,0,0,0,0,0,25,...,0,0,0,0,0,0,0,0,0,0

In [139]:
df_test_structure_own.columns

Index(['building_id', 'has_geotechnical_risk',
       'has_geotechnical_risk_fault_crack', 'has_geotechnical_risk_flood',
       'has_geotechnical_risk_land_settlement',
       'has_geotechnical_risk_landslide', 'has_geotechnical_risk_liquefaction',
       'has_geotechnical_risk_other', 'has_geotechnical_risk_rock_fall',
       'district_id', 'vdcmun_id', 'ward_id', 'count_floors_pre_eq',
       'age_building', 'plinth_area_sq_ft', 'height_ft_pre_eq',
       'land_surface_condition', 'foundation_type', 'roof_type',
       'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'legal_ownership_status', 'count_families', 'has_secondary_use',
       'has_secondary_use_agriculture', 'has_secondary_use_hotel',
       'has_secondary_use_rental', 'has_secondary_use_institution',
       'has_secondary_use_school', 'has_secondary_use_industry',
       'has_secondary_use_health_post', 'has_secondary_use_gov_office',
       'has_secondary_use_use_police', 'has_secondary_use_other'],
      dtype='object')

In [171]:
df_test_final = df_test_structure_own[[ 'district_id', 
               'has_superstructure_mud_mortar_stone', 
               'plinth_area_sq_ft',  
               'height_ft_pre_eq', 
               'has_geotechnical_risk', 
               'has_superstructure_timber', 
               'count_floors_pre_eq', 
               'age_building', 
                'building_id']]

In [172]:
df_test_final.describe()

,district_id,has_superstructure_mud_mortar_stone,plinth_area_sq_ft,height_ft_pre_eq,has_geotechnical_risk,has_superstructure_timber,count_floors_pre_eq,age_building,building_id
count,221117.000000,221117.000000,221117.000000,221117.000000,221117.000000,221117.000000,221117.000000,221117.000000,221117.000000
mean,26.842975,0.762316,417.223692,16.303943,0.124477,0.254340,2.131609,27.824301,369119.720325
std,7.775255,0.425666,230.599519,5.785338,0.330126,0.435491,0.729530,73.074036,212730.689911
min,7.000000,0.000000,70.000000,6.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,22.000000,1.000000,281.000000,13.000000,0.000000,0.000000,2.000000,10.000000,184933.000000
50%,27.000000,1.000000,364.000000,16.000000,0.000000,0.000000,2.000000,18.000000,369271.000000
75%,31.000000,1.000000,492.000000,19.000000,0.000000,1.000000,2.000000,30.000000,553578.000000
max,51.000000,1.000000,5220.000000,99.000000,1.000000,1.000000,9.000000,999.000000,737050.000000

In [118]:
df_test_final.shape

(221117, 9)

In [175]:
#df_test_final.building_id

In [173]:
# Use test and show results of test set

y_hat = model.predict(df_test_final)

In [176]:
#y_hat

#test_outcome = df_test_final.building_id&y_hat
#test_outcome

#df_test_final['building_id'] = y_hat
#df_test_final

# merge buildingID


# runden

#df_solution = pd.DataFrame(list(y_hat, df_test_final.building_id), columns=list('damage_grade', 'building_id'))

df_solution = pd.DataFrame({'building_id':df_test_final.building_id, 'damage_grade':y_hat.round()})

In [169]:
import csv
#df_solution

In [177]:
df_solution

        building_id  damage_grade
0            680648           2.0
1            339540           4.0
2            487192           5.0
3            571276           4.0
4            326396           4.0
5            398550           4.0
6            133435           3.0
7            131229           3.0
8            167591           4.0
9            178017           4.0
10            16373           4.0
11           429958           4.0
12           429931           4.0
13            44770           2.0
14            31063           3.0
15           182560           4.0
16            56489           4.0
17           345080           4.0
18           681536           2.0
19           156688           5.0
20            41180           4.0
21           427260           3.0
22           523473           2.0
23           188059           5.0
24           275266           4.0
25           695912           2.0
26           132372           4.0
27           697040           3.0
28           293418           2.0
29           417654           2.0
...             ...           ...
221087        60836           2.0
221088       426171           5.0
221089        81785           2.0
221090       508393           4.0
221091       275852           4.0
221092        27426           3.0
221093       375081           4.0
221094        99018           3.0
221095       403774           5.0
221096         8864           3.0
221097       662431           3.0
221098       157192           2.0
221099       729273           2.0
221100       174872           5.0
221101       324470           4.0
221102       167315           4.0
221103       652719           3.0
221104       204652           5.0
221105        47068           1.0
221106       151383           4.0
221107       455428           5.0
221108       498927           4.0
221109       267806           4.0
221110       545374           1.0
221111        20178           3.0
221112        28187           1.0
221113       617274           4.0
221114       485364           4.0
221115       308807           2.0
221116       509754           3.0

[221117 rows x 2 columns]

In [178]:
df_solution.to_csv (r'/Users/danielmueller/learningcenter/mckinsey/export_dataframe.csv', index = None, header=True)

In [163]:
pwd

'/Users/danielmueller/learningcenter/mckinsey'

In [166]:
df_solution

        building_id  damage_grade
0               2.5           2.0
1               4.4           4.0
2               4.9           5.0
3               3.8           4.0
4               4.0           4.0
5               4.4           4.0
6               3.3           3.0
7               2.7           3.0
8               3.8           4.0
9               4.4           4.0
10              3.6           4.0
11              4.1           4.0
12              3.5           4.0
13              2.4           2.0
14              2.8           3.0
15              4.4           4.0
16              4.0           4.0
17              4.3           4.0
18              2.0           2.0
19              4.8           5.0
20              3.9           4.0
21              3.2           3.0
22              2.3           2.0
23              4.9           5.0
24              3.8           4.0
25              2.5           2.0
26              4.1           4.0
27              3.1           3.0
28              1.5           2.0
29              2.0           2.0
...             ...           ...
221087          2.4           2.0
221088          5.0           5.0
221089          2.2           2.0
221090          3.8           4.0
221091          4.2           4.0
221092          3.0           3.0
221093          4.3           4.0
221094          2.6           3.0
221095          4.6           5.0
221096          2.6           3.0
221097          3.1           3.0
221098          1.9           2.0
221099          2.3           2.0
221100          4.9           5.0
221101          4.4           4.0
221102          4.0           4.0
221103          3.1           3.0
221104          5.0           5.0
221105          1.4           1.0
221106          4.0           4.0
221107          5.0           5.0
221108          4.2           4.0
221109          4.5           4.0
221110          1.2           1.0
221111          3.3           3.0
221112          1.2           1.0
221113          4.1           4.0
221114          4.4           4.0
221115          2.4           2.0
221116          2.8           3.0

[221117 rows x 2 columns]